# Root Logger
rootLogger.level = info
rootLogger.appenderRefs = console, file

# Console Appender
rootLogger.appenderRef.console.ref = ConsoleAppender

# File Appender
rootLogger.appenderRef.file.ref = FileAppender


# ---------------- Console Appender ----------------

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout

appender.console.layout.pattern = %d [%t] %-5level %logger{36} - %message%n


# ---------------- File Appender ----------------

appender.file.type = RollingFile
appender.file.name = FileAppender

appender.file.fileName = Logs/automation.log
appender.file.filePattern = logs/automation-%d{yyyy-MM-dd}.log.gz

appender.file.layout.type = PatternLayout

appender.file.layout.pattern = %d [%t] %-5level %logger{36} - %message%n

appender.file.policies.type = Policies

appender.file.policies.size.type = SizeBasedTriggeringPolicy
appender.file.policies.size.size = 5MB