#baseURL=http://demo.guru99.com/v3/index.php
#username=mngr382901
#password=uqupArE

#baseURL=http://dev.ukfdceauction.in/
#username=ranjankmr251@gmail.com    
#password=Ranjan@123


baseURL=http://113.193.239.230/upfclkonewui/
username=transcend
password=123456
browser=chrome

chromepath=./Drivers\\chromedriver.exe
iepath=./Drivers\\msedgedriver.exe
firefoxpath=./Drivers\\geckodriver.exe

#baseURL=http://dev.ukfdceauction.in/
#baseURL=https://113.193.239.230/ufdceauction
#username=ranjan@tipl.in
#password=Test@123
#browser=Chrome


